language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
install:
  - pip install -r requirements.txt
  - pip install coveralls 
before_script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
script:
  - python setup.py test 
  - python setup.py install
  - ./tests/system_test.sh
after_success:
  - coveralls

